### ISSUE TITLE
Error on record

### ISSUE THREAD

**Issue by esturniolo** [deep5050/radio-active#72] opened 2023-10-01 17:08 UTC
When you try to record a radio that transmit in another codec than mp3, it will fail.
https://imgur.com/LDu7pbt

May be using `-c:a libmp3lame` in the ffmpeg record command will help.
The previuos flag change the codec to mp3.

**Comment by deep5050** [comment] 2023-10-01 17:14
duplicate of #68 
yes i have checked with `libmp3lame` it works as expected 🎉 . Thanks you so much for the trick!

**Comment by deep5050** [comment] 2023-10-02 11:34
hi, @esturniolo would you please try this insider version and give feedback about the recording feature?
by default, it would record `mp3`,. if `-filetype auto` is provided it will try to detect the codec information from the URL and set the extension accordingly!

`pip install git+https://github.com/deep5050/radio-active@2.8.0`

**Comment by esturniolo** [comment] 2023-10-04 21:11
I'll.
If you can, please give me a few days.

I'm glad that the libmp3lame worked!

**Closed** 2023-10-05 11:14 UTC

**Comment by esturniolo** [comment] 2023-10-06 09:38
The recording feature now works as expected.
Thanks!

But I've another question regarding the recording.
I see that this new version doesn't show the UUID anymore, so how can I select the proper station to recording programatically?

**Comment by deep5050** [comment] 2023-10-06 10:26
actually, the table with UUID takes up a lot of space. I was planning to ignore it completely.

you can suggest me weather I should display UUID or not.

**Comment by esturniolo** [comment] 2023-10-06 14:22
I understand, but I think that this info is needed in order to record something in the background.
What about if you use on the last characters of the UUID in the screen, but pointing to the real one?

I mean you have this UUDI `5517c22e-6453-11ee-8c99-0242ac120002`

But in the screen you show:

```
┃ ID ┃ Station                        ┃ Country ┃ UUID              |         Tags                     ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 1  │ Spoon                          │         │ 0242ac120002      |                                    │
```

If not, there is another way to record in the background?

**Comment by deep5050** [comment] 2023-10-06 15:53
We can show the UUID after we select a station. Or introduce an option to show detailed search results.

**Comment by esturniolo** [comment] 2023-10-07 10:12
The idea to add an option to show the detailed view in resutls sounds great!
So every user select what to see.
